name: Add new issues to Project column
on: [issues]
jobs:
  github-actions-automate-projects:
    runs-on: ubuntu-latest
    env:
      projectname: https://github.com/${{ github.repository }}/projects/1
      
    steps:
    - name: add-new-issues-to-repository-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'issues' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: ${{env.projectname}}
        GITHUB_PROJECT_COLUMN_NAME: Inbox
